services:

  db: 
    image: postgres 
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password


  backend: 
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    volumes:
      - ./backend:/backend
    environment:
      - DB_HOST=db  # Add this line
      - RACK_ENV=development
      
  frontend:
      build: 
        context: frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes: 
        - ./frontend:/frontend
      environment:
          - NODE_ENV=development







