services:
  db: 
    image: postgres 
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backend: 
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    volumes:
      - ./backend:/backend
  frontend:
      build: 
        context: frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes: 
        - ./frontend:/frontend
      environment:
        POSTGRES_PASSWORD: password



